// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: treatments.sql

package treatmentdb

import (
	"context"

	"github.com/google/uuid"
)

const createTreatment = `-- name: CreateTreatment :one
INSERT INTO treatments
(category_id, name_treatment, description, thumbnail, price, duration, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, category_id, name_treatment, description, thumbnail, price, duration, is_active, created_at, updated_at
`

type CreateTreatmentParams struct {
	CategoryID    uuid.UUID `db:"category_id"`
	NameTreatment string    `db:"name_treatment"`
	Description   string    `db:"description"`
	Thumbnail     string    `db:"thumbnail"`
	Price         float64   `db:"price"`
	Duration      int32     `db:"duration"`
	IsActive      bool      `db:"is_active"`
}

func (q *Queries) CreateTreatment(ctx context.Context, arg CreateTreatmentParams) (Treatment, error) {
	row := q.db.QueryRow(ctx, createTreatment,
		arg.CategoryID,
		arg.NameTreatment,
		arg.Description,
		arg.Thumbnail,
		arg.Price,
		arg.Duration,
		arg.IsActive,
	)
	var i Treatment
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.NameTreatment,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTreatment = `-- name: DeleteTreatment :exec
DELETE FROM treatments WHERE id = $1
`

func (q *Queries) DeleteTreatment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTreatment, id)
	return err
}

const findTreatmentById = `-- name: FindTreatmentById :one
SELECT id, category_id, name_treatment, description, thumbnail, price, duration, is_active, created_at, updated_at FROM treatments WHERE id = $1
`

func (q *Queries) FindTreatmentById(ctx context.Context, id uuid.UUID) (Treatment, error) {
	row := q.db.QueryRow(ctx, findTreatmentById, id)
	var i Treatment
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.NameTreatment,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findTreatmentByName = `-- name: FindTreatmentByName :one
SELECT id, category_id, name_treatment, description, thumbnail, price, duration, is_active, created_at, updated_at FROM treatments WHERE name_treatment = $1
`

func (q *Queries) FindTreatmentByName(ctx context.Context, nameTreatment string) (Treatment, error) {
	row := q.db.QueryRow(ctx, findTreatmentByName, nameTreatment)
	var i Treatment
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.NameTreatment,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findTreatments = `-- name: FindTreatments :many
SELECT id, category_id, name_treatment, description, thumbnail, price, duration, is_active, created_at, updated_at FROM treatments
`

func (q *Queries) FindTreatments(ctx context.Context) ([]Treatment, error) {
	rows, err := q.db.Query(ctx, findTreatments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Treatment
	for rows.Next() {
		var i Treatment
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.NameTreatment,
			&i.Description,
			&i.Thumbnail,
			&i.Price,
			&i.Duration,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTreatment = `-- name: UpdateTreatment :one
UPDATE treatments SET
  category_id = $2,
  name_treatment = $3,
  description = $4,
  thumbnail = $5,
  price = $6,
  duration = $7,
  is_active = $8
WHERE id = $1 RETURNING id, category_id, name_treatment, description, thumbnail, price, duration, is_active, created_at, updated_at
`

type UpdateTreatmentParams struct {
	ID            uuid.UUID `db:"id"`
	CategoryID    uuid.UUID `db:"category_id"`
	NameTreatment string    `db:"name_treatment"`
	Description   string    `db:"description"`
	Thumbnail     string    `db:"thumbnail"`
	Price         float64   `db:"price"`
	Duration      int32     `db:"duration"`
	IsActive      bool      `db:"is_active"`
}

func (q *Queries) UpdateTreatment(ctx context.Context, arg UpdateTreatmentParams) (Treatment, error) {
	row := q.db.QueryRow(ctx, updateTreatment,
		arg.ID,
		arg.CategoryID,
		arg.NameTreatment,
		arg.Description,
		arg.Thumbnail,
		arg.Price,
		arg.Duration,
		arg.IsActive,
	)
	var i Treatment
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.NameTreatment,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Duration,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
