// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package role_permissionsdb

import (
	"time"

	"github.com/google/uuid"
)

type Permission struct {
	ID          uuid.UUID `db:"id"`
	Module      string    `db:"module"`
	Action      string    `db:"action"`
	Name        string    `db:"name"`
	Description string    `db:"description"`
	IsActive    bool      `db:"is_active"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
	DeletedAt   time.Time `db:"deleted_at"`
}

type Role struct {
	ID              uuid.UUID `db:"id"`
	Name            string    `db:"name"`
	Code            string    `db:"code"`
	Level           int32     `db:"level"`
	Description     string    `db:"description"`
	CanSelfRegister bool      `db:"can_self_register"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
	DeletedAt       time.Time `db:"deleted_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `db:"role_id"`
	PermissionID uuid.UUID `db:"permission_id"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
	DeletedAt    time.Time `db:"deleted_at"`
}

type User struct {
	ID              uuid.UUID `db:"id"`
	Name            string    `db:"name"`
	Email           string    `db:"email"`
	Password        string    `db:"password"`
	PhoneNumber     string    `db:"phone_number"`
	RoleID          uuid.UUID `db:"role_id"`
	IsVerified      bool      `db:"is_verified"`
	VerifyCode      string    `db:"verify_code"`
	VerifyExpiresAt time.Time `db:"verify_expires_at"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
	DeletedAt       time.Time `db:"deleted_at"`
}

type UserSession struct {
	ID        uuid.UUID `db:"id"`
	UserID    uuid.UUID `db:"user_id"`
	RefToken  string    `db:"ref_token"`
	ClientIp  string    `db:"client_ip"`
	IsBlocked bool      `db:"is_blocked"`
	ExpiresAt time.Time `db:"expires_at"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	DeletedAt time.Time `db:"deleted_at"`
}
