// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package role_permissionsdb

import (
	"context"

	"github.com/google/uuid"
)

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT
    p.module, p.action, p.name
FROM role_permissions rp
JOIN permissions p ON rp.permission_id = p.id
WHERE rp.role_id = $1::uuid AND p.is_active = true
`

type GetRolePermissionsRow struct {
	Module string `db:"module"`
	Action string `db:"action"`
	Name   string `db:"name"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, dollar_1 uuid.UUID) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolePermissionsRow
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(&i.Module, &i.Action, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
