// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package categorydb

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name_category) VALUES ($1) RETURNING id, name_category, created_at, updated_at
`

func (q *Queries) CreateCategory(ctx context.Context, nameCategory string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, nameCategory)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.NameCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const findCategories = `-- name: FindCategories :many
SELECT id, name_category, created_at, updated_at FROM categories
`

func (q *Queries) FindCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, findCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.NameCategory,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCategoryById = `-- name: FindCategoryById :one
SELECT id, name_category, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) FindCategoryById(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryById, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.NameCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCategoryByName = `-- name: FindCategoryByName :one
SELECT id, name_category, created_at, updated_at FROM categories WHERE name_category = $1
`

func (q *Queries) FindCategoryByName(ctx context.Context, nameCategory string) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByName, nameCategory)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.NameCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name_category = $2 WHERE id = $1 RETURNING id, name_category, created_at, updated_at
`

func (q *Queries) UpdateCategory(ctx context.Context, iD uuid.UUID, nameCategory string) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, iD, nameCategory)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.NameCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
