// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package roledb

import (
	"context"

	"github.com/google/uuid"
)

const getAllRoles = `-- name: GetAllRoles :many
SELECT id, name, code, level, description, can_self_register, created_at, updated_at FROM roles
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Level,
			&i.Description,
			&i.CanSelfRegister,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, name, code, level, description, can_self_register, created_at, updated_at FROM roles WHERE code = $1 LIMIT 1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Level,
		&i.Description,
		&i.CanSelfRegister,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, code, level, description, can_self_register, created_at, updated_at FROM roles r WHERE r.id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Level,
		&i.Description,
		&i.CanSelfRegister,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
