// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package permissiondb

import (
	"context"
)

const getPermissionByModuleAction = `-- name: GetPermissionByModuleAction :one
SELECT id, module, action, name, description, is_active, created_at, updated_at, deleted_at FROM permissions
WHERE module = $1 AND action = $2 AND is_active = true
LIMIT 1
`

func (q *Queries) GetPermissionByModuleAction(ctx context.Context, module string, action string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByModuleAction, module, action)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Action,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
